language: node_js
node_js:
  - node # uses most recent stable node version
services:
  - postgresql # starts up postgres
addons:
  postgresql: '9.6' # highest available postgres version on Travis
dist: trusty # uses trusty environment
sudo: false # when on trusty, uses Docker containers for speed
notifications:
  email:
    on_success: change # default: change (only when going from broken to fixed)
    on_failure: always # default: always (which is annoying, as it should be)
install:
  - npm ci # faster, goes only from package-lock
before_script:
  - psql -c 'create database "deployment-exercise-test";' -U postgres # remember to change this name if you change it elsewhere (e.g. package.json)
before_deploy: # omit node_modules, since we set skip_cleanup below
  - rm -rf node_modules
deploy: # see README for details on these keys
  # prevents travis from deleting the build
  skip_cleanup: true
  provider: heroku
  # app should be your heroku app name; see README
  app: balthazar
  # the secure key indicates an encrypted value; see README
  api_key:
    secure: IsEdrqjIYxWyo9HmeUoBMsKtbcGB3A116uB015c5YeqZ3fC3w7sAU+6bWWdXLu4s+Y6j/AH2LN3F9sA/blbcZ7hfh6UIbgxk9XxgioxuaVEWlXJzC0JGdfBCcOvlrqi8ke/aL5ISruKLRAw7JFKLwulpixjhGBTEGwpsi4lGtEsGka5krtKQXuRrUcDwBWd2dkVoBMBK8A/WZwunQWWSSjvvtDWPOCn4dKGwfsQm+2/402makBCf9HlIj8r0NNzh7xUjr0704IvY6TtqVWtM74cig5zFD61mLrLkyl4Gs6X68HpogAt99FxrMyG2xg7t21ccLP56CG2+7vqg82V6RAdwZXjf+kQmwBdSV4rnPxR8ZVG+IgA5X75O1ncdFUpug7yekEyWR79QC9Aec43q8Z1MzJ0yq6DVUgjDxy+4r3u0R1Jok6/PTLyuxL56+wXOHo+GOiREDQBRBcOqq1t/Fit3vVH+kHlMfuaccOMUIsTnyeQ9SsuEB3hOewPDRDrzFo6lJc2eCKO+I8NyMBXF/ZU1p7CiWOkHkq5qdcVWQOW+x/zd9ALHt43zMwn0M6pIdw4dsYS2Jcq4aajMroMLYJmyuKTZnDm/ejyq54vDJHwwLyP91NhRxbRXFYEatIAaQ7D5ESUl5ZyarWDcWt+sKOU6ra5PLANtjezVW25gpOs=
